### PR TITLE
fix history buttons color

### PR DESCRIPTION
**Pull request by SunsetTechuila**
## before:
image
image

## after:
image
image

### CODE REVIEW

**Review by nimsandu — APPROVED** [review]

**Comment by nimsandu** [comment]
@SunsetTechuila 
image
there is a slight issue with this pr.
i accidently reverted #179 instead of this.
could you please consider about this issue whenever you can.
and don't forget to reopen #179

**Comment by SunsetTechuila** [comment]
> there is a slight issue with this pr.
The buttons that changed in my screenshot didn't change color for you? How is that possible?

**Comment by SunsetTechuila** [comment]
I see now. I made this commit before I had a transparent panel, as I recall. That's probably the reason. Okay, will remake this

**Comment by SunsetTechuila** [comment]
You have edited my comment instead writing yours)

**Comment by nimsandu** [comment]
Oops!
😂 sorry

**Comment by nimsandu** [comment]
> I see now. I made this commit before I had a transparent panel, as I recall. That's probably the reason. Okay, will remake this

Great!

**Pull request merged**
