### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by SunsetTechuila**
for some issues mentioned in #220 and more

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
now fix #219 too

**Comment by SunsetTechuila** [comment]
and partially #223

**Comment by SunsetTechuila** [comment]
fix animation lags on hi-res screens (qhd+)

**Comment by SunsetTechuila** [comment]
and #222

**Comment by SunsetTechuila** [comment]
- ### before:
image

- ### after:
image

**Comment by SunsetTechuila** [comment]
image
this thing

**Comment by SunsetTechuila** [comment]
match and notmatch operators behave differently when used with arrays-they do not return true/false, they return strings matching the condition. -notmatch "xpui.js_find_8008" will return all strings not containing "xpui.js_find_8008", so the condition will always be true

**Comment by SunsetTechuila** [comment]
- ### before:
image


- ### after:
image

**Comment by SunsetTechuila** [comment]
- ### before:
image

- ### after:
image

**Comment by SunsetTechuila** [comment]
- ### before:
image

- ### after:
image

**Comment by SunsetTechuila** [comment]
image

**Comment by SunsetTechuila** [comment]
it was difficult, but now it seems to work with **all** languages

**Review by nimsandu — APPROVED** [review]

**Pull request merged**
