### PR TITLE
add transparency to the top bar and search field

### PR DESCRIPTION
**Pull request by SunsetTechuila**
image

image

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
image
image

image
image

**Comment by nimsandu** [comment]
@SunsetTechuila Wow that's a good one.
I looked into your prs. 
Ill merge all of them after testing them. But I promise you I won't take long.
Thanks

**Comment by SunsetTechuila** [comment]
> Wow that's a good one

I also intend to expand the background of lyrics so that it always goes beyond the top bar. I already have some options, but I haven't decided on the right one yet

**Review by nimsandu — APPROVED** [review]

**Comment by nimsandu** [comment]
@SunsetTechuila this one look stunning

**Pull request merged**
