### PR TITLE
rewrite new lyrics style

### PR DESCRIPTION
**Pull request by SunsetTechuila**
dynamic brightness (now for real) and saturation, new track change animation (now without artifacts), better overall performance (visibility hidden -> display none) and other minor changes

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
need feedback on saturation filters

**Comment by nimsandu** [comment]
> need feedback on saturation filters



> need feedback on saturation filters

looks nice @SunsetTechuila !
are we ready to merge your work?
i looked into the code and tested. everything seems fine

**Comment by SunsetTechuila** [comment]
No oversaturated or undersaturated backdrops?

**Comment by nimsandu** [comment]
> No oversaturated or undersaturated backdrops?
its the most suitable amount to me.
image

**Comment by SunsetTechuila** [comment]
> are we ready to merge your work?

now we can

**Review by nimsandu — APPROVED** [review]

**Comment by nimsandu** [comment]
done @SunsetTechuila ❤️
nice work

**Pull request merged**
