### PR TITLE
unify theme.js style to air-bnb

### PR DESCRIPTION
**Pull request by SunsetTechuila**

### CODE REVIEW

**Comment by nimsandu** [comment]
@SunsetTechuila Ill test this out in a bit mate

**Review by nimsandu — APPROVED** [review]

**Comment by nimsandu** [comment]
@SunsetTechuila Done With ❤️

**Comment by SunsetTechuila** [comment]
rewritten lyrics will be today

**Comment by nimsandu** [comment]
> rewritten lyrics will be today

🔥🔥

**Pull request merged**
