### PR TITLE
improve code style

### PR DESCRIPTION
**Pull request by SunsetTechuila**

### CODE REVIEW

**Comment by nimsandu** [comment]
@SunsetTechuila I checked your improvements and found nothing wrong. But for better security I might wait until @windowz414 review the code

**Comment by nimsandu** [comment]
@windowz414 could you please review this improvements for us?

Take your time.

Sorry If we are disturbing

**Comment by SunsetTechuila** [comment]
Yes, I did

**Comment by nimsandu** [comment]
> @nimsandu sorry for no replies, I was kind of busy with school matters and such. Let me have a quick glance at what this PR has in the store for us.
> 
> 

It's all right. You must consider your priorities

**Comment by nimsandu** [comment]
> Yes, I did

No problems at all right?

**Comment by SunsetTechuila** [comment]
of course, otherwise I would close this pull request or amend the commit

**Comment by nimsandu** [comment]
@SunsetTechuila SORRY for keep you waiting

**Pull request merged**
