### PR TITLE
make color scheme config follow current windows settings

### PR DESCRIPTION
**Pull request by SunsetTechuila**

### CODE REVIEW

**Comment by nimsandu** [comment]
@SunsetTechuila ill takes some time to check this fix. cuz this is a big addition!

**Comment by SunsetTechuila** [comment]
Maybe also add a Segoe UI Variable installation if it is missing? Installed Bloom on Windows 10 yesterday and it looked terrible with default Segoe UI font. What do you think @nimsandu ?

**Comment by nimsandu** [comment]
> Maybe also add Segoe UI Variable installation if it is missing? Installed Bloom on Windows 10 yesterday and it looked terrible with default Segoe UI font. What do you think @nimsandu ?

that would be great!
what do you think? are you going to open a separate pr or would you modify this commit?

**Comment by nimsandu** [comment]
> I'm not sure if it's big, but ok)

its not too big!
but i have a history with it 🙃

**Comment by SunsetTechuila** [comment]
> > Maybe also add Segoe UI Variable installation if it is missing? Installed Bloom on Windows 10 yesterday and it looked terrible with default Segoe UI font. What do you think @nimsandu ?
> 
> are you going to open a separate pr or would you modify this commit?

Separate ofc

**Pull request merged**
