### PR TITLE
fix(user.css): improve top bar buttons position in Linux & macOS

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**
Before:
Screenshot from 2023-12-22 00-14-50

After:
Screenshot from 2023-12-22 00-13-13

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
what about mac os?
image
maybe use `:not(.spotify__os--is-linux)`?

**Comment by TheChilledBuffalo** [comment]
@SunsetTechuila But it's only the Windows version of Spotify that has window controls like-

this
Screenshot 2023-12-22 075713

and this
Screenshot 2023-12-22 075731

-interfering with the Spotify top bar. In Linux and MacOS, the window controls and top bar are on separate rows and don't come into contact with each other. Hence, the padding and margin for the top bar and history buttons should be a windows exclusive property, don't you think?

**Comment by SunsetTechuila** [comment]
> In MacOS, the window controls and top bar are on separate rows and don't come into contact with each other. 

Ok then

**Review by SunsetTechuila — APPROVED** [review]

**Comment by SunsetTechuila** [comment]
Thanks

**Comment by TheChilledBuffalo** [comment]
@SunsetTechuila Oops, I had one more change to suggest. I was planning to add it to this PR but you had closed it before I could. Sorry for the new PR...

**Pull request merged**
