### PR TITLE
make progress bar bg transparent and more visible

### PR DESCRIPTION
**Pull request by SunsetTechuila**

### CODE REVIEW

**Comment by nimsandu** [comment]
@SunsetTechuila Can you attach a screenshot previewing this change?
I have trouble testing it right now

**Comment by SunsetTechuila** [comment]
one minute

**Comment by SunsetTechuila** [comment]
## before:
image
image

## after:
image
image

**Comment by nimsandu** [comment]
@SunsetTechuila Does this effect volume slider too?

**Comment by SunsetTechuila** [comment]
# dark mono

## before:
image

## after:
image

**Comment by SunsetTechuila** [comment]
> @SunsetTechuila Does this effect volume slider too?

yes

**Comment by SunsetTechuila** [comment]
image

It is visible, don't worry

**Comment by nimsandu** [comment]
@SunsetTechuila Light theme?

**Comment by nimsandu** [comment]
> image
> 
> 
> 
> It is visible, don't worry

Got it😀

**Comment by SunsetTechuila** [comment]
> @SunsetTechuila Light theme?

I forgot about it. I'll amend commit now

**Comment by nimsandu** [comment]
> > @SunsetTechuila Light theme?
> 
> 
> 
> I forgot about it. I'll amend commit now 

Roger that

**Comment by SunsetTechuila** [comment]
image
Now looks nice in light theme too

**Comment by SunsetTechuila** [comment]
image
Much better than it was

**Comment by nimsandu** [comment]
@SunsetTechuila Looks stunning

**Pull request merged**
