### PR TITLE
Adds color scheme based on the Zorin OS dark green colors

### PR DESCRIPTION
**Pull request by stpnwf**
In color.ini, I called it `zdarkgreen` but feel free to name it whatever makes most sense to you.

### CODE REVIEW

**Comment by nimsandu** [comment]
@stpnwf can you include some screenshots of your scheme?

**Review by nimsandu — APPROVED** [review]

**Comment by nimsandu** [comment]
image
@windowz414 @SunsetTechuila looks great right?
well done @stpnwf

**Comment by SunsetTechuila** [comment]
Yes, looks great (excluding mismatched "and" "and more"  color. I will try to do something with this)

**Comment by SunsetTechuila** [comment]
I also recently suggested to another person to do PR with his colour scheme, so maybe another cool color scheme awaits us

**Comment by nimsandu** [comment]
@SunsetTechuila 

> I also recently suggested to another person to do PR with his colour scheme, so maybe another cool color scheme awaits us

really? thats great! im currently working on a new cover image and a new color scheme pictures to be included in readme. so i ll wait for your friend to implement that scheme so i can include it too

**Comment by SunsetTechuila** [comment]
it’s better not to wait, I just saw a guy with a cool scheme and suggested that he do a PR, but he didn’t promise anything)

**Comment by nimsandu** [comment]
@SunsetTechuila alright then

**Comment by windowz414** [comment]
> image
> @windowz414 @SunsetTechuila looks great right?
> well done @stpnwf

@nimsandu looks awesome! ~~I'll finally be able to use it on Zorin without design inconsistencies. /j~~

**Comment by SunsetTechuila** [comment]
image
now looks like that

**Comment by windowz414** [comment]
All fine here.

image

**Pull request merged**
