### PR TITLE
Dev fix

### PR DESCRIPTION
**Pull request by Crushoverride007**
here's the request PR,  https://github.com/nimsandu/spicetify-bloom/issues/131#issue-1492800212

### CODE REVIEW

**Comment by windowz414** [comment]
@nimsandu, right away! Firing up my laptop already!

**Comment by windowz414** [comment]
@Crushoverride007, I can confirm that this at least doesn't break anything on my setup. But I suggest you to drop the first commit of this PR (f80772980ac5509915dc7a7b70bde5eb23994e1b). I know that a bot did that commit, but dropping that commit will make things async with Nimsandu's tree and make up less overhead.

**Comment by nimsandu** [comment]
Thank you @windowz414 
Roger that!
Merging pr

**Comment by nimsandu** [comment]
@Crushoverride007 Thanks for your effort 
And @windowz414 thanks for your review

**Comment by windowz414** [comment]
Any time @nimsandu! Thanks to you for your effort on the theme too!

**Pull request merged**
