### PR TITLE
Update LibraryX screenshots

### PR DESCRIPTION
**Pull request by nimsandu**
Addition:(libraryx style screenshots)

### CODE REVIEW

**Comment by nimsandu** [comment]
@SunsetTechuila @windowz414 what do you think?

**Comment by windowz414** [comment]
> @SunsetTechuila @windowz414 what do you think?

Looks awesome if you ask me!

**Comment by SunsetTechuila** [comment]
The style is different and the existing screenshots should also be updated imho. Otherwise - good

**Comment by SunsetTechuila** [comment]
maybe also add lyrics/transparent menus screenshots

**Comment by nimsandu** [comment]
> maybe also add lyrics/transparent menus screenshots

yah, sure i will do that!

**Comment by SunsetTechuila** [comment]
> The style is different and the existing screenshots should also be updated imho. Otherwise - good

and
image

**Comment by windowz414** [comment]
> > The style is different and the existing screenshots should also be updated imho. Otherwise - good
> 
> and image

You have an eagle's eye for real, @SunsetTechuila!

**Pull request merged**
