### PR TITLE
fix:play button not showing at launch

### PR DESCRIPTION
**Pull request by miukyo**
i changed the button size from `var(--size)` to `40px` instead. 

for some reason `var(--size)` are not existed when you launch spotify. it shown after you open artist page. idk why but here's the fix

### CODE REVIEW

**Comment by nimsandu** [comment]
@miukyo Is this issue still presents at your end?
It got fixed after installing theme again just after merging your previous pr (it seems the issue got fixed) can you conform issue?

**Comment by miukyo** [comment]
> @miukyo Is this issue still presents at your end?
> It got fixed after installing theme again just after merging your previous pr (it seems the issue got fixed) can you conform issue?

Not sure if this happen to other, it happen to me. ill check again later.

**Comment by miukyo** [comment]
@nimsandu 

i can conform this issue. i already reinstall the theme and it still happen

this what happen, when launch spotify the button not appearing when u try to hover. and when you open artist page. it will be normal again.

https://user-images.githubusercontent.com/35654409/207575134-fb0ac7dd-d7b9-4ce3-b71f-572c4613e045.mp4

and i change this value `var(--size)` to `40px` instead. the issue got fixed

https://user-images.githubusercontent.com/35654409/207576664-269c28ea-6851-42d3-a3f2-ea45befea662.mp4

**Comment by miukyo** [comment]
> @miukyo Got it!
> Merging pr
> Thank you very much 

You're welcome

**Pull request merged**
