### PR TITLE
fix playlist description color

### PR DESCRIPTION
**Pull request by SunsetTechuila**
## before:
image

## afrer:
image

### CODE REVIEW

**Comment by nimsandu** [comment]
@SunsetTechuila ❤️

**Comment by SunsetTechuila** [comment]
Dark themes have this issue too
image

**Comment by nimsandu** [comment]
@SunsetTechuila Well with the merge it should be fixed right?

**Comment by SunsetTechuila** [comment]
yep
image

**Comment by nimsandu** [comment]
@SunsetTechuila Nicely wow

**Pull request merged**
