### PR TITLE
some fix is missed

### PR DESCRIPTION
**Pull request by lemonbigbig**
sorry for that

### CODE REVIEW

**Comment by larsjuhw** [comment]
The playlist icons still don't show for me.
image

**Comment by lemonbigbig** [comment]
I don't know how do you apply the change. I double-checked it have include fully fix. I think you can wait @nimsandu merge it and re-install it.

**Comment by nimsandu** [comment]
@lemonbigbig done

**Comment by nimsandu** [comment]
Thanx bro @lemonbigbig

**Comment by nimsandu** [comment]
@larsjuhw reinstall now

**Comment by larsjuhw** [comment]
It works now, thanks!

**Pull request merged**
