### PR TITLE
fix(user.css): make icon change fast

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**
Issue: There is a delay in icons appearing when switching to a different navbar link (only the first click)

Solution: Pre-load all required icons at start-up

### CODE REVIEW

**Comment by TheChilledBuffalo** [comment]
@SunsetTechuila do you think this would be a good addition? I've currently made this a draft, will open it fully after I get feedback from you.

**Comment by SunsetTechuila** [comment]
hello, i have already experimented with prefetching:
https://pastebin.com/eEFRH1bz
prefetching doesn't completely solve the problem, but since it makes it less noticeable, i'm not against backporting this to the current script
doing this in css doesn't seem like a good idea to me, sorry

**Comment by SunsetTechuila** [comment]
`githubContentsAPIAssetsURL` = `https://[api.github.com/repos/nimsandu/spicetify-bloom/contents/assets?ref=main`
`githubPagesURL` = `https://nimsandu.github.io/spicetify-bloom`

**Comment by TheChilledBuffalo** [comment]
> doing this in css doesn't seem like a good idea to me, sorry

yeah, I thought the same about writing this in CSS too, but I don't know much JS...

>https://pastebin.com/eEFRH1bz 

Also, is this typescript? Because I can't seem to run it in the theme.js file. 

> prefetching doesn't completely solve the problem

why though?

And may I close this PR then or will you continuing developing this fix in this PR?

**Comment by SunsetTechuila** [comment]
>  is this typescript

Yes

> may I close this PR

Yes

> why though?

Because of Spotify's slow React code

**Pull request closed without merging**
