### PR TITLE
Сategory cards improvements 

### PR DESCRIPTION
**Pull request by SunsetTechuila**

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
Yes, infinite loop in the background, but we have no choice. DevTools profiler says it has almost no performance impact

**Comment by SunsetTechuila** [comment]
> DevTools profiler says it has almost no performance impact

image_2023-02-24_13-46-24

**Comment by SunsetTechuila** [comment]
> infinite loop in the background

Maybe later I'll implement this using events, but not for now

**Comment by SunsetTechuila** [comment]
will reopen when rewrite using MutationObserver

**Comment by nimsandu** [comment]
> will reopen when rewrite using MutationObserver

Roger that

**Comment by nimsandu** [comment]
@SunsetTechuila Don't get mad about me please. I still haven't had time to open up my laptop

**Comment by SunsetTechuila** [comment]
> Don't get mad about me please

Np, we all work for free here, so we have no obligations to anyone

**Comment by nimsandu** [comment]
> > Don't get mad about me please
> 
> Np, we all work for free here, so we have no obligations to anyone

but we all have that aim to help someone who chose to trust us.
that's how we can make this society better.

**Pull request closed without merging**
