### PR TITLE
fix(user.css): make eternal jukebox stats visible

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**
Made the stats of eternal jukebox that were previously hidden behind the player bar, visible. 

Also made changes so that the header doesn't stick to the top.

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
can you send a before/after pic, please?

**Comment by TheChilledBuffalo** [comment]
Before:

Screenshot 2023-12-15 150645

After:

Screenshot 2023-12-15 150728

**Comment by SunsetTechuila** [comment]
thanks for the contribution

**Comment by TheChilledBuffalo** [comment]
@SunsetTechuila Hey thank you for merging my PR. But the `improve selector` commit has made the jukebox container worse.

Screenshot 2023-12-17 234833

Screenshot 2023-12-17 234845

May I create a new PR fixing this?

**Comment by SunsetTechuila** [comment]
hello

> The stats are hidden again

fixed with https://github.com/nimsandu/spicetify-bloom/commit/91b1439abf5a09a0d4560bd4687135c145b573ad

> settings page is messed up.

fixed with https://github.com/nimsandu/spicetify-bloom/commit/8d1fc5e757852381e2436c36c79bea24e41e4ab6

**Pull request merged**
