### PR TITLE
add ms store style hover animation to main cards

### PR DESCRIPTION
**Pull request by SunsetTechuila**

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
I don't know the reason for the `transition: background-color 150ms ease` existed so I only commented it out

**Comment by SunsetTechuila** [comment]
Maybe for a smooth color scheme transition? But only a few elements have this animation

**Comment by SunsetTechuila** [comment]
that was fast)

**Comment by nimsandu** [comment]
oh i like to finish everything fast 🙂 @SunsetTechuila

**Comment by nimsandu** [comment]
well i tried the animation 
its gorgeous!

**Comment by SunsetTechuila** [comment]
thanks

**Pull request merged**
