### PR TITLE
Scheme Addition:(Ocean)

### PR DESCRIPTION
**Pull request by CharlieS1103**

### CODE REVIEW

**Comment by nimsandu** [comment]
could you please add a screenshot to show users how the scheme look like

**Comment by CharlieS1103** [comment]
@nimsandu Where would you like the screenshot to go? None of the other schemes have any.

**Comment by nimsandu** [comment]
Yap
But the ocean scheme is a contributed scheme 

So im adding the screenshot and your username as the contributor of ocean scheme

**Comment by CharlieS1103** [comment]
@nimsandu Alright, where would you like the screenshot to go in the project structure + should I add it to the readme?

**Comment by nimsandu** [comment]
@CharlieS1103 nope just add it as a comment in here
ill do the rest

**Pull request closed without merging**
