### PR TITLE
fixes the playlist icons and scroll

### PR DESCRIPTION
**Pull request by clout2k**
fixes the playlist icons and gets them from spotify instead.  scroll now allows you to view all your playlist on the left side

### CODE REVIEW

**Comment by nimsandu** [comment]
@clout2k  you sure everything's fine now?

**Comment by nimsandu** [comment]
@windowz414 sorry to bother you
can you review this fix for me please?
I'm not quite sure about myself. And I don't want to take any risks right now.
please

**Comment by clout2k** [comment]
just did more testing and it seems the height resets after a playlist/folder creation. and if you change the image of a playlist it will not update but other than that its an okay solution

**Comment by nimsandu** [comment]
@clout2k all right. great solution.
we will wait for @windowz414 to conform the fix

**Comment by nimsandu** [comment]
@windowz414 ?
are we good to go?

**Comment by nimsandu** [comment]
@windowz414 don't worry, i know you are busy. apologize me if I disturbed you.
i figured it out.

**Comment by nimsandu** [comment]
@clout2k your solution is really interesting. pictures are a bit large than it used to be and there are problems with changing picture. but everything is nice.
windowz414 must be busy these days. so sorry to keep you waiting.
thanks, and welcome to bloom community

**Comment by clout2k** [comment]
sizes can be changed with line 72, i don’t remember the original sizes or how it looked before

**Comment by nimsandu** [comment]
@clout2k nice, i enhanced it. now it feels better

**Pull request merged**
