### PR TITLE
refactor(user.css): don't change custom app icon by default

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**

### CODE REVIEW

**Review by SunsetTechuila — CHANGES_REQUESTED** [review]
@TheChilledBuffalo Hello! If we add the icon, it should be custom, otherwise we should just make the original one visible

**Comment by TheChilledBuffalo** [comment]
@SunsetTechuila hey I've made some changes. Can you take a look?

**Review by SunsetTechuila — APPROVED** [review]
i decided not to wait any longer and changed the way custom icons are applied to custom apps

**Comment by SunsetTechuila** [comment]
thank you for contributing to bloom

**Pull request merged**
