### PR TITLE
initial LibraryX support

### LINKED ISSUE #153: Conflict with the sidebar
So I have a bug that the texts conflict with the sidebar.
I am using **Spotify for Windows v1.2.4.912.g949d5fd0** and **Spicetify v2.16.1**

image

### PR DESCRIPTION
**Pull request by SunsetTechuila**
image

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
image

**Review by windowz414 — COMMENTED** [review]
Everything seems nice, but one bug I've noticed with this work. The "Your Library" icon.

image

Other than that, good work!

**Comment by SunsetTechuila** [comment]
It is not a bug, I just forgot about it)

**Comment by windowz414** [comment]
> It is not a bug, I just forgot about it)

Oh I see...

**Comment by SunsetTechuila** [comment]
fixed

**Review by windowz414 — APPROVED** [review]
LGTM.

**Comment by SunsetTechuila** [comment]
waiting for Nimsandu

**Comment by nimsandu** [comment]
- @SunsetTechuila @windowz414 Sorry for being inactive for a movement. I cant just keep you waiting for any longer. Im merging this fix without testing. Sorry for the inconvenience. It will take 2-3 days for me to test this

**Comment by nimsandu** [comment]
@SunsetTechuila Great job mate

**Comment by SunsetTechuila** [comment]
it would be great if you update screenshots and add some new ones)

**Comment by windowz414** [comment]
> it would be great if you update screenshots and add some new ones when you have time)

@nimsandu, I'll send you the screenshots on Twitter DMs.

**Comment by nimsandu** [comment]
@SunsetTechuila @windowz414 thanks for both of you! im completely exhausted these days. I'll do my best to buy some time.

**Comment by nimsandu** [comment]
image
@SunsetTechuila do you have any idea why?
libraryX ui is brilliant tbh

**Comment by SunsetTechuila** [comment]
@nimsandu done

**Comment by SunsetTechuila** [comment]
image
500 сommits now! Anniversary, right?)

**Comment by windowz414** [comment]
> 500 сommits now! Anniversary, right?)

Rather milestone :)

**Comment by nimsandu** [comment]
> image 500 сommits now! Anniversary, right?)

🥳why not?

**Pull request merged**
