### PR TITLE
connect to a device solution

### PR DESCRIPTION
**Pull request by Lseoksee**
I found a solution to #138
The 8ce57bd43bc245deb96a11a3c20b641d9de08cfc is the problem.

### CODE REVIEW

**Comment by nimsandu** [comment]
@Lseoksee Thanks for your effort 

@windowz414 can you conform this fix? It doesn't match with #138 (referenced commits on both issue and pr is different)

**Comment by windowz414** [comment]
@nimsandu, I'll try right as I turn on my laptop.

**Comment by windowz414** [comment]
@nimsandu this one fixes "Connect to device" tab, as stated by @Lseoksee stated. We can also close issue #145 in regards to this.

I'll check if the play button is all fine on Linux after applying this PR now.

**Comment by nimsandu** [comment]
all right @windowz414 thanks.
ill merge this fix and close the issue. then can you open another issue regarding linux play/pause button bug?
plaese

**Review by nimsandu — APPROVED** [review]

**Comment by nimsandu** [comment]
@Lseoksee thanks for this fix and so sorry to keep you waiting. done with ❤️

**Comment by windowz414** [comment]
> then can you open another issue regarding linux play/pause button bug? plaese

Sure, I'll open one after a day or two, currently busy with some exam stuff. ;w;

**Pull request merged**
