### PR TITLE
theme script migration

### PR DESCRIPTION
**Pull request by ohitstom**
This PR is implementing the [new theme script feature](https://github.com/spicetify/spicetify-cli/pull/2256) added in Spicetify v2.17.2.

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
Also need to add bloom.js removal if exist

**Comment by ohitstom** [comment]
> Also need to add bloom.js removal if exist

I can remove it from the config but i dont know how much sense it would make to do anything more since this is an install script and within a few updates mostly new users will be using said script anyways.

**Review by SunsetTechuila — COMMENTED** [review]
`Remove-Item -Path "$spicePath\Extensions\bloom.js" -Force -ErrorAction SilentlyContinue` would be better

**Review by SunsetTechuila — APPROVED** [review]

**Comment by SunsetTechuila** [comment]
Thanks for the quick response and contribution! This is the first time I've seen someone not only add a new feature to a parent project, but also independently implement its support in child ones) That deserves respect!

**Comment by SunsetTechuila** [comment]
@nimsandu please merge my PRs first to avoid conflict

**Review by nimsandu — APPROVED** [review]

**Comment by nimsandu** [comment]
@ohitstom @SunsetTechuila all conflicts solved and successfully merged into spicetify-bloom main

**Comment by nimsandu** [comment]
@ohitstom as sunset mentioned, you deserve our bloom communities' respect for doing such a great job by fixing not just spicetify-cli but also effected themes too.

@ohitstom we respect you for what you have done Mr. Thomas Fitzpatrick

**Pull request merged**
