### PR TITLE
use accent color for tag container

### PR DESCRIPTION
**Pull request by SunsetTechuila**
makes it colored in light theme

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
## before:
image

## after:
image

**Comment by SunsetTechuila** [comment]
I noticed it yesterday, I don't know why I ignored it

**Review by nimsandu — APPROVED** [review]

**Comment by nimsandu** [comment]
oh im sorry can you open this again.
i mistaken this with #177

**Comment by nimsandu** [comment]
@SunsetTechuila sorry

**Pull request merged**
